from .linkedin import LINKEDIN_SYSTEM_PROMPT, LINKEDIN_USER_PROMPT
from .newsletter import NEWSLETTER_SYSTEM_PROMPT, NEWSLETTER_USER_PROMPT
from .whatsapp import WHATSAPP_SYSTEM_PROMPT, WHATSAPP_USER_PROMPT

__all__ = [
    "LINKEDIN_SYSTEM_PROMPT",
    "LINKEDIN_USER_PROMPT",
    "NEWSLETTER_SYSTEM_PROMPT",
    "NEWSLETTER_USER_PROMPT",
    "WHATSAPP_SYSTEM_PROMPT",
    "WHATSAPP_USER_PROMPT",
]
